(ns minii-focus.logic.task-actions
  (:require
   [minii-focus.widgets.input-dialog :as input-dialog]
   [minii-focus.widgets.confirm-dialog :as confirm]
   [minii-focus.logic.db :as db]
   [minii-focus.logic.records :as rec]
   [minii-focus.state.store :as store]
   ["package:flutter/material.dart" :as m]))

(defn open-task-editor
  "Open task editor dialog.
   Supports both create and edit modes.
   In is-edit? mode, it will update the selected-task that the detail page is watching."
  ([ctx] (open-task-editor ctx nil))
  ([ctx task-map]
   (let [{:keys [id title notes parent-id]} task-map
         is-edit? (some? id)]
     (m/showDialog
      .context ctx
      .barrierDismissible false
      .builder
      (fn [ctx]
        (input-dialog/generic-input-dialog
         {:title (if is-edit? "ᠵᠠᠰᠠᠬᠤ" (if parent-id "ᠰᠢᠨ᠎ᠡ ᠳᠡᠳ᠋ ᠳᠠᠭᠠᠭᠠᠯᠭᠠᠪᠤᠷᠢ" "ᠰᠢᠨ᠎ᠡ ᠳᠠᠭᠠᠭᠠᠯᠭᠠᠪᠤᠷᠢ"))
          :initial-text (or title "")
          :initial-notes (or notes "")
          :on-submit (fn [new-data]
                       (let [new-title (:title new-data)
                             new-notes (:notes new-data)]
                         (if is-edit?
                           (do
                             (db/update-task! id :title-and-notes {:title new-title :notes new-notes})
                             (swap! store/app-ui-state
                                    (fn [state]
                                      (let [current-task (rec/->clj (:selected-task state))
                                            updated-task (when current-task
                                                           (merge current-task {:title new-title :notes new-notes}))]
                                        (assoc state :selected-task updated-task)))))
                           (db/add-task! {:title new-title :notes new-notes :parent-id parent-id}))
                         (m/Navigator.pop ctx)))
          :on-cancel #(m/Navigator.pop ctx)}))))))

(defn open-subtask-editor
  "Open subtask editor dialog for a parent task."
  [ctx parent-id]
  (open-task-editor ctx {:parent-id parent-id}))

(defn delete-task-confirm
  [ctx editor-ctx id]
  (confirm/show!
   ctx
   {:title "ᠤᠰᠠᠳᠬᠠᠬᠤ ᠎ᠤᠤ?"
    :message "ᠳᠠᠭᠠᠭᠠᠯᠭᠠᠪᠤᠷᠢ᠎ᠢ ᠤᠰᠠᠳᠬᠠᠬᠤ ᠎ᠤᠤ?"
    :on-confirm (fn []
                  (db/delete-task! id)
                  (when editor-ctx (m/Navigator.pop editor-ctx))
                  (when-not editor-ctx (m/Navigator.pop ctx)))}))
